- pages/product/index.tsx
- src/components/Product/index.tsx
- src/components/common/Image.tsx
- src/hooks/useLikeList.tsx
- src/interfaces/product.ts
- src/mocks/handlers/product.ts
- src/styles/GlobalStyle.tsx
- src/styles/theme.ts
- src/utils/format.ts
#9 
- 상품 컴포넌트 구현
- 이미지 공통 컴포넌트 추가
- 가격 포맷 유틸 함수 추가
- 폰트 추가 (Noto Sans KR)
> 상품 컴포넌트 구현

- package-lock.json
- package.json
- pages/product/index.tsx
- pages/search/index.tsx
- src/components/Product/index.tsx
- src/components/common/Button.tsx
- src/components/common/Input.tsx
- src/components/layout/Layout.tsx
- src/styles/GlobalStyle.tsx
- src/styles/theme.ts
#16
- 최근 검색어 레이아웃 추가
- 추천 검색어 레이아웃 추가
- 검색버튼 클릭 시 상품 목록 출력
> 상품 검색 페이지 구현중

- package-lock.json
- package.json
- pages/index.tsx
- src/styles/GlobalStyle.tsx
#10 
- 디자인이 아직 나오지 않은 관계로 구조만 미리 잡아보았습니다...
https://user-images.githubusercontent.com/107393773/225524518-b46b67d3-a46b-4e7f-87c4-7b86ab7fba42.mov
- Swiper를 설치하였으니 `npm i swiper` 한번씩 부탁드려욥 😁
- 디자인 변경 될 수 있습니다!! 지금은 예시로만 봐주세요
> 메인 페이지 구조 정리

- package-lock.json
- package.json
- pages/product/index.tsx
- pages/search/index.tsx
- src/components/common/Modal.tsx
- src/components/layout/Layout.tsx
- src/constants/messages.ts
- src/interfaces/modal.ts
- src/store/index.tsx
- src/store/modal.tsx
- src/utils/storage.ts
#16 
- 최근 검색어 저장 기능 구현
- 로컬 스토리지 유틸 함수 추가
- 공통 모달 컴포넌트 추가
- react-modal 패키지를 설치해주세요.
> 최근 검색어 저장 기능 구현

- pages/cart/index.tsx
- src/components/Cart/CartItem.tsx
- src/components/common/Image.tsx
- src/interfaces/cart.ts
- src/utils/format.ts
#25 
- 장바구니 레이아웃 구현
- 장바구니 인터페이스 수정
- 총 예약 금액 계산 로직 추가
- 기간 포맷팅 함수 추가
> 장바구니 레이아웃 구현

- pages/community/notice/index.tsx
- pages/community/review/index.tsx
- src/constants/routes.ts
- src/dummydata/communityReview.json
- src/interfaces/community.ts
#44 
- 리뷰, 공지사항 경로 수정
- 더미데이터 폴더 생성
- [커뮤니티] 후기 목록 페이지 구현 중
> Feat: 커뮤니티-리뷰, 공지사항 라우터 수정 및 더미데이터 생성

- package-lock.json
- package.json
- pages/_app.tsx
- pages/product/index.tsx
- pages/search/index.tsx
- pages/survey/index.tsx
- src/components/Product/ProductItem.tsx
- src/components/common/Image.tsx
- src/components/common/ScrollTop.tsx
- src/components/layout/Layout.tsx
- src/styles/GlobalStyle.tsx
- src/utils/storage.ts
#16 
- 최근 검색어 선택삭제 / 전체삭제 기능 구현
- 최근 검색어 자동저장 켜기/끄기 기능 구현
- 상품 목록에 출발일자 / 인원 수 / 정렬 방법 옵션 추가
- ProductItem 컴포넌트에 미디어 쿼리 추가
- CookiesProvider 추가
- 공통 ScrollTop 버튼 추가
npm i 명령어로 react-datepicker 라이브러리를 설치해 주세요!
> 검색 페이지 최근 검색어 관련 기능 구현

- package-lock.json
- package.json
- pages/admin/product/category/edit.tsx
- pages/mypage/index.tsx
- src/components/Mypage/GetMyinfo.tsx
- src/components/Mypage/Withdrawal.tsx
- src/styles/GlobalStyle.tsx
#50 
- 마이페이지 랜덤 프로필 이미지 적용
랜덤 프로필 이미지 라이브러리를 설치했으니 npm i 명렁어 사용 부탁드려요!
> 마이페이지 랜덤 프로필 이미지 적용

- pages/cart/index.tsx
- pages/mypage/index.tsx
- pages/mypage/order/index.tsx
- pages/mypage/review/index.tsx
- pages/mypage/wish/index.tsx
- pages/survey/index.tsx
- src/components/layout/Header.tsx
- src/components/layout/Layout.tsx
- src/components/layout/Navbar.tsx
- src/components/layout/header/Login_header.tsx
- src/components/layout/header/Logo.tsx
- src/components/layout/header/Mypage_header.tsx
#28 
전체적인 레이아웃 수정
- 페이지 컴포넌트에 padding: 16px; 적용 부탁드려요!
- 피그마 레이아웃이 IPhone 12 Mini 기준이기 때문에 
브라우저 화면에서 해당 크기로 확인하면서 작업하시는 게 좋을 것 같아요!
> 전체적인 레이아웃 수정

- src/components/Mypage/Wish/WishCard.tsx
- src/components/common/PageTitle.tsx
- src/styles/GlobalStyle.tsx
- src/styles/muiTheme.ts
#2 
font-weight 400, 500, 600 적용
기본 폰트 크기 14px 로 설정 
기본 폰트 색상 #101010 으로 적용
> 디자인 가이드 적용

- pages/survey/index.tsx
- src/components/Product/ProductCard.tsx
- src/components/common/ScrollTop.tsx
#23 
- 테스트 4단계로 설정
- 카드 클릭 시 다음 단계로 이동
- 테스트 완료 후 유형 보여주기
> 여행 유형 테스트 스텝퍼 설정

- package-lock.json
- package.json
- pages/community/review/[id].tsx
- pages/community/review/add.tsx
- pages/community/review/index.tsx
- pages/review/index.tsx
- src/components/Community/ReviewItem.tsx
- src/constants/routes.ts
#44
- 페이지네이션 추가
- 여행후기 관련 라우터 수정 및 파일 추가
- 모바일화면 css 수정
- 현재 모바일 화면에서 보았을 때 페이지네이션이 가려지는데 이것은 푸터가 생성되면 해결될 것 같습니다.
> 커뮤니티-여행후기 모바일 화면 수정 및 페이지네이션 추가

- package-lock.json
- package.json
- pages/community/notice/index.tsx
- pages/community/review/add.tsx
- public/icons/arrow-left.svg
- src/components/common/Editor.tsx
#64 
- 리뷰 작성 페이지를 구현하였습니다.
https://user-images.githubusercontent.com/107393773/229462636-7571cbfd-39e0-42bc-ae83-8b20ef8487d8.mov
https://user-images.githubusercontent.com/107393773/229463911-d21e1536-4444-4b5c-875f-2ddb9acd4317.mov
- editor를 사용하였습니다. `npm i react-quill` 한번씩 부탁드려욥
- api는 후에 연결 예정입니다.
> [커뮤니티] 후기 작성 페이지 구현

- package-lock.json
- package.json
- pages/community/review/add.tsx
- pages/community/review/edit.tsx
#67 
- 후기 작성 페이지와 동일합니다.
- 후기 상세 페이지 구현 후 수정 페이지에 들어가면 상세 페이지 내용이 보이도록 하려고 합니다.
> Feat: [커뮤니티] 후기 수정 페이지 구현

- package-lock.json
- package.json
- pages/community/review/[id].tsx
- pages/community/review/add.tsx
- pages/community/review/edit.tsx
- pages/product/[id].tsx
- src/components/Community/ReviewItem.tsx
- src/components/common/Editor.tsx
- src/dummydata/reviewDetail.json
- src/interfaces/community.ts
- src/utils/format.ts
#69 
- 후기 상세 페이지 구현 중입니다.
- 디자인이 없는 상태라 원래 홈페이지 참고하여 구현중입니다.
- react-quill 이미지 처리하는 중에 계속 오류가 나서 에디터 toast ui 로 변경하였습니다.
- `npm install @toast-ui/react-editor @toast-ui/editor-plugin-color-syntax` 한번씩 해주세엽
> [커뮤니티] 후기 페이지 구현 중 & 에디터 변경

- pages/community/review/[id].tsx
- src/dummydata/reviewDetail.json
#69 
- 후기 상세 페이지 구현중입니다
- 후기 수정 페이지 api 연결 확인을 위해 PR올립니당
> [커뮤니티]후기 상세 페이지 구현중

- pages/community/review/edit.tsx
- src/apis/community.ts
- src/constants/apiUrls.ts
#67 
- api 경로 추가
- 후기 수정 페이지 api 연결
> [커뮤니티] 후기 수정 페이지 api 연결

- pages/community/review/edit.tsx
- pages/community/review/index.tsx
- src/components/Community/ReviewItem.tsx
- src/constants/messages.ts
#49 
- 후기쓰기 버튼 클릭시 토큰이 없으면 로그인 페이지로 이동
> [커뮤니티] 후기 목록 페이지 수정

- pages/community/notice/index.tsx
- pages/community/review/edit.tsx
- pages/community/review/index.tsx
- src/apis/community.ts
- src/constants/apiUrls.ts
- src/constants/messages.ts
> [커뮤니티] 공지사항[알려드려요] api 연결

- pages/community/notice/[id].tsx
- pages/community/notice/index.tsx
- pages/community/review/[id].tsx
- pages/community/review/edit.tsx
- pages/community/review/index.tsx
- src/apis/community.ts
- src/components/Community/NoticeItem.tsx
- src/constants/apiUrls.ts
- src/constants/messages.ts
#84 
- 알려드려요 상세 페이지 구현
- 주석처리 되어 있는 부분은 알려드려요에 있는 글의 내용이 일반 문자열로 되어 있어 오류가 발생하여 처리하였습니다.
- 에디터로 작성된 내용의 경우 오류가 발생하지 않습니다.
> [커뮤니티] 알려드려요 상세 페이지 구현

- pages/admin/product/[id].tsx
- pages/admin/product/add.tsx
- pages/admin/product/category/index.tsx
- pages/admin/product/edit.tsx
- pages/admin/product/index.tsx
- pages/admin/product/recommend/index.tsx
- src/apis/admin/category.ts
- src/apis/admin/recommend.ts
- src/constants/apiUrls.ts
#60 
- [관리자 페이지] 상품 상세 페이지 수정
- 현재인원, 현재싱글룸 삭제 (백엔드 요청)
- 상품 카테고리 관리 / 추천 상품 관리 페이징 api url 추가
> [관리자 페이지] 상품 상세 페이지 수정

- pages/admin/product/edit.tsx
- pages/mypage/reservation.tsx
- src/components/layout/Header.tsx
> 배포 작업을 위한 에러 수정

- pages/admin/product/[id].tsx
- pages/admin/product/add.tsx
- src/components/layout/Header.tsx
- src/utils/format.ts
#60 
- 가장 하위 카테고리 선택 시에만 카테고리로 추가되도록 수정
- 추천유형 관련 유틸 함수 추가
> [관리자 페이지] 상품 추가 카테고리 관련 수정

- package-lock.json
- pages/community/review/[id].tsx
- pages/mypage/review/[id].tsx
- pages/mypage/review/index.tsx
- src/apis/mypage/review.ts
- src/components/Mypage/Review/ReviewList.tsx
- src/components/Mypage/Review/[id].tsx
- src/constants/apiUrls.ts
- src/constants/routes.ts
- src/dummydata/MyReviewList.json
- src/interfaces/myReview.ts
#99 
- 나의 리뷰 상세 페이지 화면 구현 및 api 연결
> [마이페이지]나의 리뷰 상세 페이지 구현

- pages/product/index.tsx
- src/apis/product.ts
- src/components/Search/Search.tsx
- src/components/layout/header/SearchHeader.tsx
- src/components/layout/nav/NavCateD1.tsx
- src/constants/apiUrls.ts
#9 
#16 
- 상품 검색 페이지 구현
- 추천 상품 목록 api 연동
- 상품 목록 페이지 구현
- 내브바에서 카테고리 클릭 시 해당 카테고리 상품 목록 출력
> 상품 검색 및 목록 페이지 구현

- package-lock.json
- pages/mypage/info/index.tsx
- pages/signup/index.tsx
- src/components/Main/PopularRegion.tsx
> [로그인페이지] 에러 해결

- pages/_app.tsx
- pages/index.tsx
- pages/product/[id].tsx
- src/apis/product.ts
- src/apis/wishlist.ts
- src/components/Main/PopularRegion.tsx
- src/constants/apiUrls.ts
- src/constants/messages.ts
- src/dummydata/productDetail.json
- src/dummydata/relatedProducts.json
- src/dummydata/wishList.json
- src/interfaces/product.ts
- src/interfaces/wishlist.ts
#21 
- 상품 상세 페이지 구현 중입니다.
- 웹 화면 구현 후 모바일 화면 구현하려고 합니다.
> 상품 상세 페이지 구현

- pages/mypage/wish/index.tsx
- src/apis/mypage/wish.ts
- src/components/Mypage/Wish/WishCard.tsx
- src/constants/apiUrls.ts
- src/constants/routes.ts
- src/interfaces/wishlist.ts
#50 
- 나의 관심 상품 구현중
- 백엔드 변경사항 배포 후 재작업 예정
> 나의 관심 상품 구현중

- README.md
- package-lock.json
- pages/cart/index.tsx
- src/apis/cart.ts
#25 
#124
- 장바구니 기능 구현중
- 리드미 파일 수정
각자 리드미 파일에 추가하고 싶은 내용을 반영하여 PR 날려주시면 감사하겠습니다!
> 장바구니 기능 구현중 및 리드미 파일 수정

- pages/survey/index.tsx
- src/constants/messages.ts
#23 
- 여행 유형 테스트 시 필수로 답변 선택하도록 수정
> 여행 유형 테스트 시 필수로 답변 선택하도록 수정

- pages/_app.tsx
- src/components/common/Input.tsx
- src/components/layout/Header.tsx
- src/components/layout/Layout.tsx
- src/components/layout/nav/Depth2.tsx
- src/components/layout/nav/Depth3.tsx
- src/components/layout/nav/NavCateD1.tsx
#28 
- 검색페이지 레이아웃 헤더 수정
- 레이아웃 라우터 수정
- 리프레시 토큰 시간 수정
> [레이아웃] 검색페이지 헤더 수정/ 라우터 수정/ 리프레시 토큰 시간 수정

- pages/community/notice/index.tsx
- pages/product/[id].tsx
- src/apis/wishlist.ts
- src/components/Main/Banner.tsx
- src/constants/apiUrls.ts
- src/constants/messages.ts
> 상품 상세 페이지 - 위시리스트 관련 수정

- pages/cart/index.tsx
- src/apis/cart.ts
- src/components/Cart/CartCard.tsx
- src/constants/apiUrls.ts
- src/interfaces/cart.ts
- src/store/cart.tsx
- src/utils/format.ts
#25 
- api 응답 데이터 수정 요청 및 인터페이스 수정
- 바로 예약 버튼 클릭 시 해당 데이터를 라우터에 담아 예약 페이지로 이동
> 장바구니 기능 구현중

- src/components/layout/header/apis.ts
> [레이아웃] 리프레시 토큰 api 수정

- public/icons/survey/UserMinus.svg
- public/icons/survey/UserPlus.svg
- src/components/common/Editor.tsx
#5 
- react-draft-wysiwyg 에디터 관련 에러 수정
> 에디터 관련 에러 수정

- pages/admin/community/notice/add.tsx
- pages/admin/community/notice/edit.tsx
- pages/admin/community/review/add.tsx
- pages/admin/community/review/edit.tsx
- pages/admin/product/add.tsx
- pages/admin/product/edit.tsx
- pages/community/review/add.tsx
- pages/community/review/edit.tsx
- src/components/common/Editor.tsx
#5 
- 에디터 관련 에러 수정
- next 에서 에디터를 import 하는 모든 부분에 async / await 추가
- 배포 작업
> 에디터 관련 에러 수정 및 배포 작업

- pages/community/review/[id].tsx
- pages/community/review/index.tsx
- pages/mypage/order/[id].tsx
- src/components/Mypage/apis.ts
- src/components/Search/Search.tsx
- src/components/common/PasswordModal.tsx
- src/constants/messages.ts
#143 
- 공통 메시지 상수 파일 수정
- 객체 구조 및 텍스트 수정
> 공통 메시지 상수 파일 수정

- pages/cart/index.tsx
- src/components/Cart/CartCard.tsx
- src/store/cart.tsx
#25 
- 장바구니 선택 삭제 기능 구현
- 장바구니 카드에서 삭제버튼 클릭 시 삭제 기능 구현
- 상품 수정 시 총 합계액에 반영되도록 수정
> 장바구니 삭제 기능 구현

- pages/admin/banner/[id].tsx
- pages/admin/banner/add.tsx
- pages/admin/banner/edit.tsx
- pages/index.tsx
- pages/product/[id].tsx
- pages/survey/index.tsx
- src/components/Main/Banner.tsx
- src/components/Main/BestProducts.tsx
- src/components/Main/GroupProduct.tsx
- src/components/Main/GroupTrip.tsx
- src/components/Main/PopularRegion.tsx
- src/dummydata/bannerList.json
- src/interfaces/banner.ts
- src/interfaces/main.ts
#118
#10 
- 배너 api가 수정 됨에 따라 배너 관련 페이지를 수정하였습니다.
> 메인페이지 배너 ( + 메인 페이지 클릭하는 부분들 cursor 추가)
> 관리자 페이지 -> 배너 관리 - 상세, 추가, 수정
- 배너 추가 / 수정 페이지에서 살짝쿵 react-hook-form을 적용해보았습니다.
> 배너 관련 수정 및 메인 cursor 추가

- pages/admin/product/add.tsx
- pages/admin/product/edit.tsx
- pages/product/[id].tsx
- pages/survey/index.tsx
- src/apis/admin/category.ts
- src/apis/admin/product.ts
- src/apis/admin/recommend.ts
- src/apis/cart.ts
- src/apis/user.ts
- src/components/Cart/CartCard.tsx
- src/interfaces/base.ts
- src/interfaces/product.ts
#60 
- api 호출 함수명 통일
- get* / post*/ patch* / delete*
> api 호출 함수명 통일

- pages/community/notice/[id].tsx
- pages/community/notice/index.tsx
- pages/community/review/[id].tsx
- pages/community/review/index.tsx
- src/components/Community/CommunityRouter.tsx
- src/components/Community/NoticeItem.tsx
- src/components/Community/ReviewItem.tsx
- 커뮤니티 가로 너비 수정
- cursor: pointer 추가
- 상세의 이전 / 다음 페이지 1차적인 수정 ( -> 추가 수정이 필요할것 같습니다.)
> 커뮤니티 페이지 관련 수정

- .env
> 카카오맵 key 추가

- pages/admin/product/recommend/edit.tsx
- src/apis/product.ts
#16
- 검색 컴포넌트 호출 추천 상품 api url 수정
> 검색 컴포넌트 호출 추천 상품 api url 수정

- package-lock.json
- pages/order/index.tsx
- pages/order/success.tsx
- src/components/layout/nav/NavCateD1.tsx
close : #157 
- 결제 페이지 api연동
- 결제 페이지 css 완료
- 결제 성공 페이지 css 완료
> [결제페이지] api 연동, css 작업

- pages/admin/order/index.tsx
- pages/signup/success.tsx
- src/components/Admin/Order/AdminOrderTable.tsx
- src/components/Admin/Order/orderColumns.ts
- src/components/Admin/User/UserTable.tsx
- src/components/Login/apis.ts
- src/components/SignIn/apis.ts
close : #159 
- 관리자페이지 예약관리 api 연동
- 관리자페이지 예약관리 css 작업
- 회원가입 성공 페이지 css 작업
- 내일 전체적으로 리펙토링 진행할게요.
> [관리자 페이지] 예약관리 css, api 작업

- package-lock.json
- pages/index.tsx
- pages/mypage/info/index.tsx
- pages/mypage/wish/index.tsx
- pages/survey/index.tsx
- src/components/Cart/CartCard.tsx
- src/components/Mypage/Wish/WishCard.tsx
- src/components/Product/ProductCard.tsx
- src/components/layout/Header.tsx
- src/components/layout/MyPageNavbar.tsx
- src/components/layout/Navbar.tsx
- src/components/layout/header/MyCartHeader.tsx
- src/components/layout/header/SearchHeader.tsx
- src/constants/layoutRoutes.ts
#143 
- 내브바 레이아웃 수정
- 마이페이지 버튼 추가, 로그인/로그아웃 버튼 아이콘 추가
- 여행준비 하위 메뉴에 여행 유형 테스트 추가
> 내브바 레이아웃 수정 / 관심 상품 목록 레이아웃 수정
